// GameCube / Wii (libogc) platform layer.
#ifndef HV_PC
#include "platform/platform.h"

#include <aesndlib.h>
#include <malloc.h>
#include <ogc/lwp_watchdog.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>

#include "assets_pak.h"   // generated by bin2o from data/assets.pak

#define FIFO_SIZE (512 * 1024)

static GXRModeObj *s_rmode;
static void *s_xfb[2];
static int s_fb;
static void *s_fifo;
static u64 s_lastTime;
static f32 s_dt = 1.0f / 60.0f;
static u32 s_frame;
static u16 s_prevHeld;

void *hvAlignedAlloc(size_t size) { return memalign(32, (size + 31) & ~31u); }
void hvAlignedFree(void *p) { free(p); }

void hvLog(const char *fmt, ...) {
    (void)fmt;
#ifdef HV_DEBUG
    va_list ap;
    va_start(ap, fmt);
    char buf[256];
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    SYS_Report("%s\n", buf);
#endif
}

namespace plat {

void init() {
    VIDEO_Init();
    PAD_Init();
    s_rmode = VIDEO_GetPreferredMode(NULL);
    s_xfb[0] = MEM_K0_TO_K1(SYS_AllocateFramebuffer(s_rmode));
    s_xfb[1] = MEM_K0_TO_K1(SYS_AllocateFramebuffer(s_rmode));
    VIDEO_Configure(s_rmode);
    VIDEO_ClearFrameBuffer(s_rmode, s_xfb[0], COLOR_BLACK);
    VIDEO_ClearFrameBuffer(s_rmode, s_xfb[1], COLOR_BLACK);
    VIDEO_SetNextFramebuffer(s_xfb[0]);
    VIDEO_SetBlack(false);
    VIDEO_Flush();
    VIDEO_WaitVSync();
    if (s_rmode->viTVMode & VI_NON_INTERLACE) VIDEO_WaitVSync();

    s_fifo = memalign(32, FIFO_SIZE);
    memset(s_fifo, 0, FIFO_SIZE);
    GX_Init(s_fifo, FIFO_SIZE);

    GXColor black = {0, 0, 0, 255};
    GX_SetCopyClear(black, 0x00FFFFFF);
    GX_SetViewport(0, 0, s_rmode->fbWidth, s_rmode->efbHeight, 0, 1);
    f32 yscale = GX_GetYScaleFactor(s_rmode->efbHeight, s_rmode->xfbHeight);
    u32 xfbHeight = GX_SetDispCopyYScale(yscale);
    GX_SetScissor(0, 0, s_rmode->fbWidth, s_rmode->efbHeight);
    GX_SetDispCopySrc(0, 0, s_rmode->fbWidth, s_rmode->efbHeight);
    GX_SetDispCopyDst(s_rmode->fbWidth, xfbHeight);
    GX_SetCopyFilter(s_rmode->aa, s_rmode->sample_pattern, GX_TRUE, s_rmode->vfilter);
    GX_SetFieldMode(s_rmode->field_rendering, ((s_rmode->viHeight == 2 * s_rmode->xfbHeight) ? GX_ENABLE : GX_DISABLE));
    GX_SetPixelFmt(GX_PF_RGB8_Z24, GX_ZC_LINEAR);
    GX_SetCullMode(GX_CULL_BACK);
    GX_CopyDisp(s_xfb[s_fb], GX_TRUE);
    GX_SetDispCopyGamma(GX_GM_1_0);

    AESND_Init();
    s_lastTime = gettime();
}

void shutdown() {}
void setArgs(int, char **) {}

int screenW() { return s_rmode->fbWidth; }
int screenH() { return s_rmode->efbHeight; }
bool widescreen() {
#ifdef HW_RVL
    return CONF_GetAspectRatio() == CONF_ASPECT_16_9;
#else
    return false;
#endif
}

void endFrame() {
    GX_SetZMode(GX_TRUE, GX_LEQUAL, GX_TRUE);
    GX_SetColorUpdate(GX_TRUE);
    GX_CopyDisp(s_xfb[s_fb], GX_TRUE);
    GX_DrawDone();
    VIDEO_SetNextFramebuffer(s_xfb[s_fb]);
    VIDEO_Flush();
    VIDEO_WaitVSync();
    s_fb ^= 1;
    u64 now = gettime();
    f32 dt = ticks_to_microsecs(now - s_lastTime) / 1000000.0f;
    s_lastTime = now;
    if (dt > 0.1f) dt = 0.1f;
    if (dt < 0.001f) dt = 0.001f;
    s_dt = dt;
    s_frame++;
}

f32 frameDelta() { return s_dt; }
u32 frameCount() { return s_frame; }
u64 timeMicros() { return ticks_to_microsecs(gettime()); }

static f32 stickAxis(s8 v, int dead, int range) {
    int a = v;
    int s = a < 0 ? -1 : 1;
    a = a * s;
    if (a <= dead) return 0.0f;
    f32 f = (f32)(a - dead) / (f32)(range - dead);
    if (f > 1.0f) f = 1.0f;
    return f * s;
}

void pollInput(PadState &p) {
    u32 conn = PAD_ScanPads();
    p.connected = (conn & 1) != 0;
    u16 held = PAD_ButtonsHeld(0);
    p.pressed = held & ~s_prevHeld;
    p.released = s_prevHeld & ~held;
    p.held = held;
    s_prevHeld = held;
    p.sx = stickAxis(PAD_StickX(0), 12, 80);
    p.sy = stickAxis(PAD_StickY(0), 12, 80);
    p.cx = stickAxis(PAD_SubStickX(0), 12, 70);
    p.cy = stickAxis(PAD_SubStickY(0), 12, 70);
    p.l = PAD_TriggerL(0) / 200.0f;
    p.r = PAD_TriggerR(0) / 200.0f;
    if (p.l > 1) p.l = 1;
    if (p.r > 1) p.r = 1;
}

void rumble(bool on) { PAD_ControlMotor(0, on ? PAD_MOTOR_RUMBLE : PAD_MOTOR_STOP); }

// ------------------------------------------------------------- saves
static u8 s_cardWork[CARD_WORKAREA_SIZE] ATTRIBUTE_ALIGN(32);
static const char *kSaveName = "hearthvale.sav";

static bool cardMount() {
    static bool inited = false;
    if (!inited) {
        CARD_Init("HVAL", "HV");
        inited = true;
    }
    for (int tries = 0; tries < 10; tries++) {
        s32 r = CARD_Mount(CARD_SLOTA, s_cardWork, NULL);
        if (r >= 0) return true;
    }
    return false;
}

bool saveWrite(const void *data, u32 size) {
    if (!cardMount()) return false;
    u32 sector = 8192;
    CARD_GetSectorSize(CARD_SLOTA, &sector);
    u32 total = (size + sector - 1) / sector * sector;
    card_file f;
    s32 r = CARD_Open(CARD_SLOTA, kSaveName, &f);
    if (r == CARD_ERROR_NOFILE) r = CARD_Create(CARD_SLOTA, kSaveName, total, &f);
    if (r < 0) {
        CARD_Unmount(CARD_SLOTA);
        return false;
    }
    u8 *buf = (u8 *)memalign(32, total);
    memset(buf, 0, total);
    memcpy(buf, data, size);
    r = CARD_Write(&f, buf, total, 0);
    free(buf);
    CARD_Close(&f);
    CARD_Unmount(CARD_SLOTA);
    return r >= 0;
}

s32 saveRead(void *data, u32 maxSize) {
    if (!cardMount()) return -1;
    u32 sector = 8192;
    CARD_GetSectorSize(CARD_SLOTA, &sector);
    card_file f;
    if (CARD_Open(CARD_SLOTA, kSaveName, &f) < 0) {
        CARD_Unmount(CARD_SLOTA);
        return -1;
    }
    u32 total = (maxSize + sector - 1) / sector * sector;
    if (total > f.len) total = f.len;
    u8 *buf = (u8 *)memalign(32, total);
    s32 r = CARD_Read(&f, buf, total, 0);
    if (r >= 0) memcpy(data, buf, total < maxSize ? total : maxSize);
    free(buf);
    CARD_Close(&f);
    CARD_Unmount(CARD_SLOTA);
    return r < 0 ? -1 : (s32)(total < maxSize ? total : maxSize);
}

bool saveExists() {
    if (!cardMount()) return false;
    card_file f;
    bool ok = CARD_Open(CARD_SLOTA, kSaveName, &f) >= 0;
    if (ok) CARD_Close(&f);
    CARD_Unmount(CARD_SLOTA);
    return ok;
}

const u8 *assetData(u32 *size) {
    *size = assets_pak_size;
    DCFlushRange((void *)assets_pak, assets_pak_size);
    return assets_pak;
}

// ------------------------------------------------------------- audio
static AudioCallback s_audioCb;
static void *s_audioUser;

static void aesndCallback(void *buffer, u32 len, void *) {
    if (s_audioCb) {
        s_audioCb((s16 *)buffer, len / 4, s_audioUser);
        DCFlushRange(buffer, len);
    }
}

void audioStart(AudioCallback cb, void *user) {
    s_audioCb = cb;
    s_audioUser = user;
    AESND_RegisterAudioCallbackWithArg(aesndCallback, NULL);
    AESND_Pause(false);
}

bool quitRequested() { return false; }
bool wantsFrameRendered() { return true; }

}  // namespace plat
#endif
