// GameCube / Wii (libogc) platform layer.
#ifndef HV_PC
#include "platform/platform.h"

#include <malloc.h>
#include <math.h>
#include <ogc/lwp.h>
#include <ogc/lwp_watchdog.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#ifdef HW_RVL
#include <fat.h>
#include <wiiuse/wpad.h>
#endif

#include "assets_pak.h"   // generated by bin2o from data/assets.pak

#define FIFO_SIZE (512 * 1024)

static GXRModeObj *s_rmode;
static void *s_xfb[2];
static int s_fb;
static void *s_fifo;
static u64 s_lastTime;
static f32 s_dt = 1.0f / 60.0f;
static u32 s_frame;
static u16 s_prevHeld;
static volatile bool s_quit = false;
static volatile bool s_powerOff = false;

static void resetCallback(u32, void *) { s_quit = true; }
#ifdef HW_RVL
static bool s_sdOk = false;
static void powerCallback() {
    s_powerOff = true;
    s_quit = true;
}
static void wpadPowerCallback(s32) {
    s_powerOff = true;
    s_quit = true;
}
#endif

void *hvAlignedAlloc(size_t size) { return memalign(32, (size + 31) & ~31u); }
void hvAlignedFree(void *p) { free(p); }

void hvLog(const char *fmt, ...) {
    (void)fmt;
#ifdef HV_DEBUG
    va_list ap;
    va_start(ap, fmt);
    char buf[256];
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    SYS_Report("%s\n", buf);
#endif
}

namespace plat {

void init() {
    VIDEO_Init();
    PAD_Init();
    SYS_SetResetCallback(resetCallback);
#ifdef HW_RVL
    // Wii: Classic Controller support, HOME / power buttons, SD card saves
    WPAD_Init();
    SYS_SetPowerCallback(powerCallback);
    WPAD_SetPowerButtonCallback(wpadPowerCallback);
    s_sdOk = fatInitDefault();
#endif
    s_rmode = VIDEO_GetPreferredMode(NULL);
    s_xfb[0] = MEM_K0_TO_K1(SYS_AllocateFramebuffer(s_rmode));
    s_xfb[1] = MEM_K0_TO_K1(SYS_AllocateFramebuffer(s_rmode));
    VIDEO_Configure(s_rmode);
    VIDEO_ClearFrameBuffer(s_rmode, s_xfb[0], COLOR_BLACK);
    VIDEO_ClearFrameBuffer(s_rmode, s_xfb[1], COLOR_BLACK);
    VIDEO_SetNextFramebuffer(s_xfb[0]);
    VIDEO_SetBlack(false);
    VIDEO_Flush();
    VIDEO_WaitVSync();
    if (s_rmode->viTVMode & VI_NON_INTERLACE) VIDEO_WaitVSync();

    s_fifo = memalign(32, FIFO_SIZE);
    memset(s_fifo, 0, FIFO_SIZE);
    GX_Init(s_fifo, FIFO_SIZE);

    GXColor black = {0, 0, 0, 255};
    GX_SetCopyClear(black, 0x00FFFFFF);
    GX_SetViewport(0, 0, s_rmode->fbWidth, s_rmode->efbHeight, 0, 1);
    f32 yscale = GX_GetYScaleFactor(s_rmode->efbHeight, s_rmode->xfbHeight);
    u32 xfbHeight = GX_SetDispCopyYScale(yscale);
    GX_SetScissor(0, 0, s_rmode->fbWidth, s_rmode->efbHeight);
    GX_SetDispCopySrc(0, 0, s_rmode->fbWidth, s_rmode->efbHeight);
    GX_SetDispCopyDst(s_rmode->fbWidth, xfbHeight);
    GX_SetCopyFilter(s_rmode->aa, s_rmode->sample_pattern, GX_TRUE, s_rmode->vfilter);
    GX_SetFieldMode(s_rmode->field_rendering, ((s_rmode->viHeight == 2 * s_rmode->xfbHeight) ? GX_ENABLE : GX_DISABLE));
    GX_SetPixelFmt(GX_PF_RGB8_Z24, GX_ZC_LINEAR);
    GX_SetCullMode(GX_CULL_BACK);
    GX_CopyDisp(s_xfb[s_fb], GX_TRUE);
    GX_SetDispCopyGamma(GX_GM_1_0);

    s_lastTime = gettime();
}

void shutdown() {
    GX_AbortFrame();
    GX_Flush();
    VIDEO_SetBlack(true);
    VIDEO_Flush();
    VIDEO_WaitVSync();
    AUDIO_StopDMA();
    AUDIO_RegisterDMACallback(NULL);
#ifdef HW_RVL
    WPAD_Shutdown();
    if (s_powerOff) SYS_ResetSystem(SYS_POWEROFF, 0, 0);
#endif
    // returning from main() goes back to the loader (Homebrew Channel / Swiss)
}
void setArgs(int, char **) {}

int screenW() { return s_rmode->fbWidth; }
int screenH() { return s_rmode->efbHeight; }
bool widescreen() {
#ifdef HW_RVL
    return CONF_GetAspectRatio() == CONF_ASPECT_16_9;
#else
    return false;
#endif
}

void endFrame() {
    GX_SetZMode(GX_TRUE, GX_LEQUAL, GX_TRUE);
    GX_SetColorUpdate(GX_TRUE);
    GX_CopyDisp(s_xfb[s_fb], GX_TRUE);
    GX_DrawDone();
    VIDEO_SetNextFramebuffer(s_xfb[s_fb]);
    VIDEO_Flush();
    VIDEO_WaitVSync();
    s_fb ^= 1;
    u64 now = gettime();
    f32 dt = ticks_to_microsecs(now - s_lastTime) / 1000000.0f;
    s_lastTime = now;
    if (dt > 0.1f) dt = 0.1f;
    if (dt < 0.001f) dt = 0.001f;
    s_dt = dt;
    s_frame++;
}

f32 frameDelta() { return s_dt; }
u32 frameCount() { return s_frame; }
u64 timeMicros() { return ticks_to_microsecs(gettime()); }

static f32 stickAxis(s8 v, int dead, int range) {
    int a = v;
    int s = a < 0 ? -1 : 1;
    a = a * s;
    if (a <= dead) return 0.0f;
    f32 f = (f32)(a - dead) / (f32)(range - dead);
    if (f > 1.0f) f = 1.0f;
    return f * s;
}

#ifdef HW_RVL
static f32 ccAxis(const joystick_t &js, bool y) {
    f32 mag = js.mag;
    if (!(mag > 0.12f)) return 0.0f;   // also rejects NaN before calibration
    if (mag > 1.0f) mag = 1.0f;
    mag = (mag - 0.12f) / 0.88f;
    f32 a = js.ang * (3.14159265f / 180.0f);
    return (y ? cosf(a) : sinf(a)) * mag;
}
static f32 pickAxis(f32 a, f32 b) { return fabsf(b) > fabsf(a) ? b : a; }
#endif

void pollInput(PadState &p) {
    u32 conn = PAD_ScanPads();
    p.connected = (conn & 1) != 0;
    u16 held = PAD_ButtonsHeld(0) & 0x1F7F;
    p.sx = stickAxis(PAD_StickX(0), 12, 80);
    p.sy = stickAxis(PAD_StickY(0), 12, 80);
    p.cx = stickAxis(PAD_SubStickX(0), 12, 70);
    p.cy = stickAxis(PAD_SubStickY(0), 12, 70);
    p.l = PAD_TriggerL(0) / 200.0f;
    p.r = PAD_TriggerR(0) / 200.0f;
#ifdef HW_RVL
    WPAD_ScanPads();
    u32 wb = WPAD_ButtonsHeld(0);
    if (wb & (WPAD_BUTTON_HOME | WPAD_CLASSIC_BUTTON_HOME)) s_quit = true;
    expansion_t exp;
    WPAD_Expansion(0, &exp);
    if (exp.type == WPAD_EXP_CLASSIC) {
        // Classic Controller laid out like the GameCube pad
        p.connected = true;
        static const u32 map[][2] = {
            {WPAD_CLASSIC_BUTTON_A, BTN_A},      {WPAD_CLASSIC_BUTTON_B, BTN_B},
            {WPAD_CLASSIC_BUTTON_X, BTN_X},      {WPAD_CLASSIC_BUTTON_Y, BTN_Y},
            {WPAD_CLASSIC_BUTTON_ZR, BTN_Z},     {WPAD_CLASSIC_BUTTON_ZL, BTN_Z},
            {WPAD_CLASSIC_BUTTON_FULL_L, BTN_L}, {WPAD_CLASSIC_BUTTON_FULL_R, BTN_R},
            {WPAD_CLASSIC_BUTTON_PLUS, BTN_START}, {WPAD_CLASSIC_BUTTON_MINUS, BTN_START},
            {WPAD_CLASSIC_BUTTON_UP, BTN_UP},    {WPAD_CLASSIC_BUTTON_DOWN, BTN_DOWN},
            {WPAD_CLASSIC_BUTTON_LEFT, BTN_LEFT}, {WPAD_CLASSIC_BUTTON_RIGHT, BTN_RIGHT},
        };
        for (auto &m : map)
            if (wb & m[0]) held |= (u16)m[1];
        const classic_ctrl_t &cc = exp.classic;
        p.sx = pickAxis(p.sx, ccAxis(cc.ljs, false));
        p.sy = pickAxis(p.sy, ccAxis(cc.ljs, true));
        p.cx = pickAxis(p.cx, ccAxis(cc.rjs, false));
        p.cy = pickAxis(p.cy, ccAxis(cc.rjs, true));
        f32 l = (wb & WPAD_CLASSIC_BUTTON_FULL_L) ? 1.0f : cc.l_shoulder;
        f32 r = (wb & WPAD_CLASSIC_BUTTON_FULL_R) ? 1.0f : cc.r_shoulder;
        if (l > p.l) p.l = l;
        if (r > p.r) p.r = r;
    }
#endif
    if (p.l > 1) p.l = 1;
    if (p.r > 1) p.r = 1;
    p.pressed = held & ~s_prevHeld;
    p.released = s_prevHeld & ~held;
    p.held = held;
    s_prevHeld = held;
}

void rumble(bool on) { PAD_ControlMotor(0, on ? PAD_MOTOR_RUMBLE : PAD_MOTOR_STOP); }

// ------------------------------------------------------------- saves
static u8 s_cardWork[CARD_WORKAREA_SIZE] ATTRIBUTE_ALIGN(32);
static const char *kSaveName = "hearthvale.sav";

static bool cardMount() {
    static bool inited = false;
    if (!inited) {
        CARD_Init("HVAL", "HV");
        inited = true;
    }
    for (int tries = 0; tries < 10; tries++) {
        s32 r = CARD_Mount(CARD_SLOTA, s_cardWork, NULL);
        if (r >= 0) return true;
    }
    return false;
}

#ifdef HW_RVL
static const char *kSdDir = "sd:/apps/hearthvale";
static const char *kSdPath = "sd:/apps/hearthvale/hearthvale.sav";
static bool sdWrite(const void *data, u32 size) {
    mkdir("sd:/apps", 0777);
    mkdir(kSdDir, 0777);
    char tmp[64];
    snprintf(tmp, sizeof(tmp), "%s.tmp", kSdPath);
    FILE *f = fopen(tmp, "wb");
    if (!f) return false;
    bool ok = fwrite(data, 1, size, f) == size;
    ok = (fclose(f) == 0) && ok;
    if (!ok) return false;
    remove(kSdPath);
    return rename(tmp, kSdPath) == 0;
}
static s32 sdRead(void *data, u32 maxSize) {
    FILE *f = fopen(kSdPath, "rb");
    if (!f) return -1;
    s32 n = (s32)fread(data, 1, maxSize, f);
    fclose(f);
    return n;
}
#endif

static bool cardWrite(const void *data, u32 size);
static s32 cardRead(void *data, u32 maxSize);
static bool cardExists();

bool saveWrite(const void *data, u32 size) {
#ifdef HW_RVL
    if (s_sdOk && sdWrite(data, size)) return true;
#endif
    return cardWrite(data, size);
}

s32 saveRead(void *data, u32 maxSize) {
#ifdef HW_RVL
    if (s_sdOk) {
        s32 n = sdRead(data, maxSize);
        if (n > 0) return n;
    }
#endif
    return cardRead(data, maxSize);
}

bool saveExists() {
#ifdef HW_RVL
    if (s_sdOk) {
        FILE *f = fopen(kSdPath, "rb");
        if (f) {
            fclose(f);
            return true;
        }
    }
#endif
    return cardExists();
}

static bool cardWrite(const void *data, u32 size) {
    if (!cardMount()) return false;
    u32 sector = 8192;
    CARD_GetSectorSize(CARD_SLOTA, &sector);
    u32 total = (size + sector - 1) / sector * sector;
    card_file f;
    s32 r = CARD_Open(CARD_SLOTA, kSaveName, &f);
    if (r == CARD_ERROR_NOFILE) r = CARD_Create(CARD_SLOTA, kSaveName, total, &f);
    if (r < 0) {
        CARD_Unmount(CARD_SLOTA);
        return false;
    }
    u8 *buf = (u8 *)memalign(32, total);
    memset(buf, 0, total);
    memcpy(buf, data, size);
    r = CARD_Write(&f, buf, total, 0);
    free(buf);
    CARD_Close(&f);
    CARD_Unmount(CARD_SLOTA);
    return r >= 0;
}

static s32 cardRead(void *data, u32 maxSize) {
    if (!cardMount()) return -1;
    u32 sector = 8192;
    CARD_GetSectorSize(CARD_SLOTA, &sector);
    card_file f;
    if (CARD_Open(CARD_SLOTA, kSaveName, &f) < 0) {
        CARD_Unmount(CARD_SLOTA);
        return -1;
    }
    u32 total = (maxSize + sector - 1) / sector * sector;
    if (f.len > 0 && total > (u32)f.len) total = (u32)f.len;
    u8 *buf = (u8 *)memalign(32, total);
    s32 r = CARD_Read(&f, buf, total, 0);
    if (r >= 0) memcpy(data, buf, total < maxSize ? total : maxSize);
    free(buf);
    CARD_Close(&f);
    CARD_Unmount(CARD_SLOTA);
    return r < 0 ? -1 : (s32)(total < maxSize ? total : maxSize);
}

static bool cardExists() {
    if (!cardMount()) return false;
    card_file f;
    bool ok = CARD_Open(CARD_SLOTA, kSaveName, &f) >= 0;
    if (ok) CARD_Close(&f);
    CARD_Unmount(CARD_SLOTA);
    return ok;
}

const u8 *assetData(u32 *size) {
    *size = assets_pak_size;
    DCFlushRange((void *)assets_pak, assets_pak_size);
    return assets_pak;
}

// ------------------------------------------------------------- audio
// The game's mixer runs in its own thread (so it may use the FPU) and fills
// one half of a double buffer while the audio interface DMAs the other.
#define AUDIO_BUF_BYTES 3840   // 20 ms of 48 kHz stereo s16
static u8 s_audioBuf[2][AUDIO_BUF_BYTES] ATTRIBUTE_ALIGN(32);
static volatile u32 s_audioCur = 0;
static AudioCallback s_audioCb;
static void *s_audioUser;
static lwpq_t s_audioQueue;
static lwp_t s_audioThread;
static u8 s_audioStack[16384] ATTRIBUTE_ALIGN(8);

static void *audioThread(void *) {
    for (;;) {
        LWP_ThreadSleep(s_audioQueue);
        u8 *buf = s_audioBuf[s_audioCur];
        s_audioCb((s16 *)buf, AUDIO_BUF_BYTES / 4, s_audioUser);
        DCFlushRange(buf, AUDIO_BUF_BYTES);
    }
    return NULL;
}

static void audioDmaCallback() {
    s_audioCur ^= 1;
    AUDIO_InitDMA((u32)s_audioBuf[s_audioCur], AUDIO_BUF_BYTES);
    LWP_ThreadSignal(s_audioQueue);
}

void audioStart(AudioCallback cb, void *user) {
    s_audioCb = cb;
    s_audioUser = user;
    memset(s_audioBuf, 0, sizeof(s_audioBuf));
    DCFlushRange(s_audioBuf, sizeof(s_audioBuf));
    AUDIO_Init(NULL);
    AUDIO_SetDSPSampleRate(AI_SAMPLERATE_48KHZ);
    LWP_InitQueue(&s_audioQueue);
    if (LWP_CreateThread(&s_audioThread, audioThread, NULL, s_audioStack, sizeof(s_audioStack), 80) < 0) return;
    s_audioCur = 0;
    AUDIO_RegisterDMACallback(audioDmaCallback);
    AUDIO_InitDMA((u32)s_audioBuf[0], AUDIO_BUF_BYTES);
    AUDIO_StartDMA();
}

bool quitRequested() { return s_quit; }
bool wantsFrameRendered() { return true; }

}  // namespace plat
#endif
